### ISSUE TITLE
태스트

### ISSUE THREAD

**Issue by cdy212** [codechobostudy/scala-springboot#1]
ㄴ

**Comment by scarfunk** [comment]
## NAVER - http://www.naver.com/

scarfunk@naver.com 님께 보내신 메일 <[scala-springboot] 태스트 (#1)> 이 다음과 같은 이유로 전송 실패했습니다.

---

받는 사람이 회원님의 메일을 수신차단 하였습니다. 

---

**Comment by scarfunk** [comment]
## NAVER - http://www.naver.com/

scarfunk@naver.com 님께 보내신 메일 <Re: [scala-springboot] 태스트 (#1)> 이 다음과 같은 이유로 전송 실패했습니다.

---

받는 사람이 회원님의 메일을 수신차단 하였습니다. 

---
